language: cpp
os: linux
dist: bionic
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo dpkg --add-architecture i386
  - sudo apt -y update
  - sudo apt -y install qemu-user-static:i386
services:
  - docker
compiler:
  - gcc
jobs:
  include:
  - name: "armhf raspbian stretch"
    env: DOCKERFILE=Dockerfile-armhf-raspbian-stretch
  - name: "armhf raspbian buster"
    env: DOCKERFILE=Dockerfile-armhf-raspbian-buster
script: docker build -f $DOCKERFILE --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .
